# Generated by Django 4.1.5 on 2024-01-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("socialaccount", "0003_extra_data_default_dict"),
        ("citizenScience", "0002_extendedsocialaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedsocialaccount",
            name="social_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="socialaccount.socialaccount",
            ),
        ),
    ]
