# Generated by Django 4.1.5 on 2024-01-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citizenScience", "0003_alter_extendedsocialaccount_social_account"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExtendedSocialAccount",
        ),
    ]
